from pages.base_page import BasePage

class CoursePage(BasePage):
    def __init__(self, page):
        super().__init__(page)

    def login(self, mail: str, password: str) -> None:
        self.fill("#email", mail)
        self.fill("#password-field", password)
        self.page.get_by_role("button", name="Sign In with Mail").click()
        self.wait_for_network()

    def navigate_to_courses(self) -> None:
        self.page.get_by_role("link", name="Courses ").click()
        self.page.get_by_role("link", name="List Courses").click()
        self.wait_for_network()

    def search_course(self, course_name: str) -> None:
        self.page.get_by_role("textbox", name="Search By Title or Ref").fill(course_name)
        self.page.get_by_role("textbox", name="Search By Title or Ref").press("Enter")
        self.wait_for_network()

    def add_course(self, course_ref: str, title: str, file_path: str) -> None:
        self.page.get_by_role("link", name=" Add Course").click()
        self.wait_for_network()
        self.page.locator("select[name=\"Format\"]").select_option("XAPI")
        self.page.locator("input[name=\"CourseRef\"]").fill(course_ref)
        self.page.get_by_role("button", name="Choose File").set_input_files(file_path)
        self.page.locator("input[name=\"Title\"]").fill(title)
        self.page.locator("#AllowedAttempts").select_option("3")
        self.page.locator(".input-group-addon").click()
        self.page.locator("body").press("Enter")
        self.page.get_by_role("button", name="Save", exact=True).click()
        self.wait_for_network()

# def run(playwright: Playwright) -> None:
#     browser = playwright.chromium.launch(headless=False)
#     context = browser.new_context()
#     page = context.new_page()
#     page.goto("https://qaautomationtesting1.empowerlms.com/")
#     page.locator("#email").fill("aagam.d+1@empowerelearning.com")
#     page.locator("#password-field").click()
#     page.locator("#password-field").fill("Aagam@2026")
#     page.get_by_role("button", name="Sign In with Mail").click()
#     page.get_by_role("link", name="Courses ").click()
#     page.get_by_role("link", name="List Courses").click()
#     page.get_by_role("textbox", name="Search By Title or Ref").click()
#     page.get_by_role("textbox", name="Search By Title or Ref").click()
#     page.get_by_role("textbox", name="Search By Title or Ref").fill("test_")
#     page.get_by_role("textbox", name="Search By Title or Ref").press("Enter")
#     page.get_by_role("textbox", name="Search By Title or Ref").fill("")
#     page.get_by_label("102550100All records per page").select_option("100")
#     page.get_by_role("link", name=" Add Course").click()
#     page.locator("select[name=\"Format\"]").select_option("XAPI")
#     page.locator("input[name=\"CourseRef\"]").click()
#     page.get_by_role("button", name="Choose File").click()
#     page.get_by_role("button", name="Choose File").set_input_files("Infosec Course (2).zip")
#     page.locator("input[name=\"CourseRef\"]").click()
#     page.locator("input[name=\"CourseRef\"]").fill("test_infosec_course")
#     page.locator("input[name=\"CourseRef\"]").press("ControlOrMeta+a")
#     page.locator("input[name=\"CourseRef\"]").press("ControlOrMeta+c")
#     page.locator("input[name=\"Title\"]").click()
#     page.locator("input[name=\"Title\"]").fill("test_infosec_course")
#     page.locator("#AllowedAttempts").select_option("3")
#     page.locator(".input-group-addon").click()
#     page.locator("body").press("Enter")
#     page.get_by_role("cell", name="4").first.click()
#     page.get_by_role("button", name="Save", exact=True).click()
#     page.goto("https://qaautomationtesting1.empowerlms.com/admin/course")
#     page.get_by_role("textbox", name="Search By Title or Ref").click()
#     page.get_by_role("textbox", name="Search By Title or Ref").fill("test_infose")
#     page.get_by_role("textbox", name="Search By Title or Ref").press("Enter")
#     page.get_by_role("link", name="test_infosec_course").click()
#     page.get_by_role("link", name="  Cancel").click()
#     page.get_by_role("textbox", name="Search By Title or Ref").click()
#     page.get_by_role("textbox", name="Search By Title or Ref").fill("test_info")
#     page.get_by_role("textbox", name="Search By Title or Ref").press("Enter")
#     page.get_by_role("link", name="test_infosec_course").click()
#     page.get_by_role("link", name="Users").click()
#     page.locator("#userAssessmentForm").click()
#     page.get_by_role("list").filter(has_text=re.compile(r"^$")).click()
#     page.get_by_role("treeitem", name="Aagam", exact=True).click()
#     page.get_by_role("treeitem", name="Aagam Agency User").click()
#     page.get_by_role("treeitem", name="Aagam Learner").click()
#     page.get_by_text("×").nth(1).click()
#     page.get_by_text("×").nth(1).click()
#     page.get_by_role("button", name="Submit").click()
#     page.get_by_text("Assignment", exact=True).click()
#     page.get_by_role("link", name="  View as User").click()
#     page.get_by_role("link", name="Courses").click()
#     page.get_by_role("link", name="test_infosec_course ").click()
#     page.get_by_role("cell", name="/3").click()
#     page.get_by_role("button", name="Close").click()
#     with page.expect_popup() as page1_info:
#         page.locator("#cert-download").get_by_role("link", name="Start").click()
#     page1 = page1_info.value
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("The purpose of this").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:20$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":131x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":131x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:43$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator(".continue-hint").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator(".continue-hint").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:34$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("main").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:26$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":221x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:34$")).nth(2).click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Mute").nth(2).click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("slider", name="Volume").nth(2).fill("100")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="What Happens When This Is").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Mute").nth(2).click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Complete the content above").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Play").nth(1).click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Play").nth(1).click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Pause").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Pause").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Pause").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("label").filter(has_text="It protects information and").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("quiz-submit-button").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Complete the content above").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:39$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Foundations of Information SecurityLesson 4 of 11OverviewFoundations of").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Foundations of Information SecurityLesson 4 of 11OverviewFoundations of").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Foundations of Information SecurityLesson 4 of 11OverviewFoundations of").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:48$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowDown")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowDown")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowUp")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowUp")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("combobox", name="Play speed").nth(1).click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("option", name="2x").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:18$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":141x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:25$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(2).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(2).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(2).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(2).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(2).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(2).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":181x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":181x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Keeping information accurate").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("quiz-submit-button").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:37$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Common Information Security").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Common Information Security").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Common Information Security").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:14$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("combobox", name="Play speed").nth(1).click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("option", name="2x").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:21$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":141x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Pause").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Pause").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Play").nth(3).click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:19$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Pause").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Pause").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Pause").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":131x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:44$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").nth(3).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").nth(3).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Common Information Security ThreatsLesson 5 of 11Social EngineeringSocial").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":421x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":371x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Play").nth(4).click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Because users can be").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("quiz-submit-button").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:27$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Password and Account Security").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Password and Account Security").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Password and Account Security").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Password and Account Security").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Password and Account Security").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Password and Account Security").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:27$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Password and Account Security").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Password and Account Security").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("timer", name="seconds").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("combobox", name="Play speed").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("option", name="1.75x").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:29$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:29$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":221x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:16$")).first.dblclick()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":141x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(2).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(2).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(2).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(2).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:13$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(2).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(2).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(2).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:13$")).first.dblclick()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":071x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:37$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":221x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":221x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Complete the content above").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Play").nth(4).click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Creating strong, unique passwords for each system").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("quiz-submit-button").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:26$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Safe Handling of Information").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Safe Handling of Information").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Safe Handling of Information").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Safe Handling of Information").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:26$")).first.dblclick()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:35$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":331x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:13$")).first.dblclick()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":131x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":131x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:13$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Play").nth(3).click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Play").nth(3).click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Pause").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Pause").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Pause").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="Play").nth(3).click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":321x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("To ensure information is").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("quiz-submit-button").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:48$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Secure Work Practices").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Secure Work Practices").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Secure Work Practices").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:10$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:44$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").nth(1).press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:44$")).first.dblclick()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":311x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":311x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:44$")).first.dblclick()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("label").filter(has_text="Using trusted networks and").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("quiz-submit-button").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:42$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Security Incidents & Reporting").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Security Incidents & Reporting").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Security Incidents & Reporting").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("heading", name="Security Incidents & Reporting").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:48$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:48$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":411x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("To limit impact and prevent").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("paragraph").filter(has_text="To complete documentation").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("quiz-submit-button").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="TAKE AGAIN").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("label").filter(has_text="To limit impact and prevent").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("quiz-submit-button").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:24$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("group", name="Audio player").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:42$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Continued").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":351x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:42$")).first.click()
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":351x").press("ArrowRight")
#     page1.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page1.close()
#     page.goto("https://qaautomationtesting1.empowerlms.com/courses")
#     page.get_by_role("link", name="test_infosec_course ").click()
#     page.get_by_role("button", name="Close").click()
#     with page.expect_popup() as page2_info:
#         page.get_by_role("link", name="Resume").click()
#     page2 = page2_info.value
#     page.goto("https://qaautomationtesting1.empowerlms.com/courses")
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:14$")).first.click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":071x").press("ArrowRight")
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":351x").press("ArrowRight")
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:43$")).first.click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":421x").press("ArrowRight")
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":421x").press("ArrowRight")
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":421x").press("ArrowRight")
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:43$")).first.click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^0:43$")).first.click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text(":302x").press("ArrowRight")
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Verify information before").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("quiz-submit-button").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("continue-btn").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("div").filter(has_text=re.compile(r"^Lesson 11 of 11QuizSTART QUIZ$")).nth(3).click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_test_id("quiz-start-button").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("label").filter(has_text="Accidental sharing of").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="SUBMIT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="NEXT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("label").filter(has_text="To allow the computer to").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="SUBMIT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="NEXT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("It prevents an attacker from").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("label").filter(has_text="It makes it easier for the IT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="SUBMIT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="NEXT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("label").filter(has_text="Reply to the email to ask if").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="SUBMIT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="NEXT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("label").filter(has_text="Classify the information type").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="SUBMIT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="NEXT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Non-repudiation", exact=True).click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="SUBMIT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="NEXT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_text("Use human judgment to verify").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="SUBMIT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="NEXT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator("label").filter(has_text="Automated System Prompts").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="SUBMIT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="NEXT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator(".quiz-card.quiz-card--active > .quiz-card__container > .quiz-card__row > .quiz-card__main > div > .quiz-card__interactive > div > div > div:nth-child(3) > .quiz-multiple-choice-option > .quiz-multiple-choice-option__indicator").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator(".quiz-card.quiz-card--active > .quiz-card__container > .quiz-card__row > .quiz-card__main > div > .quiz-card__interactive > div > div > div:nth-child(3) > .quiz-multiple-choice-option > .quiz-multiple-choice-option__indicator").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="SUBMIT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="NEXT").click()
#     page3 = context.new_page()
#     page3.goto("https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dm%26oq%3Dm%26gs_lcrp%3DEgZjaHJvbWUyBggAEEUYOdIBCDEwNzVqMGoxqAIAsAIA%26sourceid%3Dchrome%26ie%3DUTF-8%26sei%3DYiaDaYeGFcvQ1e8P6bTZ4QU&q=EgQOw0ymGOLMjMwGIjDfFLy5gClqfeiuzX4o4yPDV0LFeSim_pK6slYzyfR3K5no0FV7wGqYZvFn4P5nVnIyAVJaAUM")
#     page3.locator("iframe[name=\"a-qtk5z9w4bk7m\"]").content_frame.get_by_role("checkbox", name="I'm not a robot").click()
#     page3.close()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.locator(".quiz-card.quiz-card--active > .quiz-card__container > .quiz-card__row > .quiz-card__main > div > .quiz-card__interactive > div > div > div:nth-child(2) > .quiz-multiple-choice-option > .quiz-multiple-choice-option__indicator").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="SUBMIT").click()
#     page2.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="NEXT").click()
#     page2.close()
#     page.goto("https://qaautomationtesting1.empowerlms.com/courses")
#     page.get_by_role("link", name="test_infosec_course ").click()
#     page.get_by_role("button", name="Close").click()
#     with page.expect_popup() as page4_info:
#         page.get_by_role("link", name="Re-Take").click()
#     page4 = page4_info.value
#     page.goto("https://qaautomationtesting1.empowerlms.com/courses")
#     page4.locator("iframe[name=\"SCO\"]").content_frame.locator("iframe[name=\"scormdriver_content\"]").content_frame.get_by_role("button", name="EXIT COURSE").click()
#     page4.close()
#     page.goto("https://qaautomationtesting1.empowerlms.com/courses")
#     page.get_by_role("link", name="  View as Admin").click()
#     page.get_by_role("link", name="Courses ").click()
#     page.get_by_role("link", name="Categories").click()
#     page.get_by_role("link", name=" Add Category").click()
#     page.get_by_role("textbox").fill("test_course")
#     page.get_by_role("textbox").press("Enter")
#     page.get_by_role("button", name="Save", exact=True).click()
#     page.get_by_role("link", name="Team ").click()
#     page.get_by_role("link", name="Users").click()
#     page.get_by_role("textbox", name="Search by Name or Email").click()
#     page.get_by_role("textbox", name="Search by Name or Email").fill("test_info")
#     page.get_by_role("textbox", name="Search by Name or Email").press("Enter")
#     page.get_by_role("textbox", name="Search by Name or Email").fill("info")
#     page.get_by_role("textbox", name="Search by Name or Email").press("Enter")
#     page.get_by_role("textbox", name="Search by Name or Email").press("Enter")
#     page.get_by_role("textbox", name="Search by Name or Email").press("Enter")
#     page.get_by_role("textbox", name="Search by Name or Email").fill("test")
#     page.get_by_role("textbox", name="Search by Name or Email").press("Enter")
#     page.get_by_role("link", name=" Search").click()
#     page.get_by_role("link", name="Courses ").click()
#     page.get_by_role("link", name="Courses ").click()
#     page.get_by_role("link", name="List Courses").click()
#     page.get_by_role("textbox", name="Search By Title or Ref").click()
#     page.get_by_role("textbox", name="Search By Title or Ref").fill("test_")
#     page.get_by_role("textbox", name="Search By Title or Ref").press("Enter")
#     page.get_by_role("link", name="test_infosec_course").click()
#     page.get_by_role("link", name="Reports").click()
#     page.get_by_role("link", name="Get").nth(1).click()

#     # ---------------------
#     context.close()
#     browser.close()


# with sync_playwright() as playwright:
#     run(playwright)
